In [2]:
import torch

In [3]:
b, time, freq = 8, 5, 10
input_stft = torch.rand(b, time, freq)
print(input_stft)

tensor([[[6.1901e-01, 4.6692e-01, 2.4651e-01, 4.2515e-01, 8.4848e-01,
          4.3830e-01, 1.4011e-02, 9.5817e-01, 2.9340e-01, 8.5340e-01],
         [9.9212e-01, 8.1627e-01, 8.8082e-01, 9.8587e-01, 8.5174e-02,
          9.6942e-01, 7.7334e-01, 1.1601e-01, 1.8846e-01, 8.1077e-01],
         [6.6610e-01, 6.8279e-01, 9.5018e-01, 2.9599e-01, 1.5159e-01,
          9.4404e-01, 6.4279e-01, 7.7873e-01, 3.1083e-01, 1.8331e-01],
         [8.7383e-01, 4.4899e-01, 3.1787e-02, 6.5868e-01, 7.6502e-01,
          3.2638e-01, 7.8873e-01, 2.9181e-01, 3.8828e-01, 1.3746e-01],
         [7.7731e-01, 6.8488e-01, 7.4294e-01, 4.3966e-02, 8.7485e-01,
          3.7373e-01, 7.8976e-01, 7.9644e-01, 9.5351e-01, 8.0611e-01]],

        [[9.4915e-01, 4.5299e-01, 2.7888e-03, 6.9879e-01, 7.6017e-02,
          6.3283e-01, 2.4988e-01, 8.7961e-01, 9.1951e-03, 9.1881e-01],
         [4.2068e-01, 7.9694e-01, 9.6601e-01, 9.1249e-01, 6.8666e-01,
          9.3985e-01, 3.8069e-01, 1.7157e-01, 4.8130e-01, 1.0081e-01],
         [6

In [4]:
freq_window = 2
cols_to_zero = torch.randint(low=0, high=freq-freq_window, size=(b,))
print(cols_to_zero)

mask = torch.ones((b, time, freq))
mask[torch.arange(b).unsqueeze(1), :,cols_to_zero.unsqueeze(1)+torch.arange(freq_window)] = 0
zero_masked = input_stft * mask

tensor([6, 7, 7, 6, 4, 6, 1, 5])


In [5]:
mask[0,:,:]

tensor([[1., 1., 1., 1., 1., 1., 0., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 0., 1., 1.]])

In [6]:
mask[0,:,:].shape

torch.Size([5, 10])

In [7]:
# Now for the time domain:
time_window = 2

NameError: name 'batc' is not defined

In [8]:
rows_to_zero = torch.randint(low=0, high=time - 2, size=(b,))
mask = torch.ones((b, time, freq))
mask[torch.arange(b).unsqueeze(1), rows_to_zero.unsqueeze(1) + torch.arange(2), :] = 0
print(input_stft*mask)

tensor([[[0.6190, 0.4669, 0.2465, 0.4252, 0.8485, 0.4383, 0.0140, 0.9582,
          0.2934, 0.8534],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.8738, 0.4490, 0.0318, 0.6587, 0.7650, 0.3264, 0.7887, 0.2918,
          0.3883, 0.1375],
         [0.7773, 0.6849, 0.7429, 0.0440, 0.8749, 0.3737, 0.7898, 0.7964,
          0.9535, 0.8061]],

        [[0.9491, 0.4530, 0.0028, 0.6988, 0.0760, 0.6328, 0.2499, 0.8796,
          0.0092, 0.9188],
         [0.4207, 0.7969, 0.9660, 0.9125, 0.6867, 0.9398, 0.3807, 0.1716,
          0.4813, 0.1008],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.4426, 0.3962, 0.9076, 0.2541, 0.9396, 0.0229, 0.1835, 0.5364,
          0.066

In [16]:
input = torch.ones(3,6,8)
print(torch.tensor([1, 2, 3]).unsqueeze(1).shape)
print(torch.eye(8).unsqueeze(0).shape)
print(torch.tensor([1, 2, 3]).unsqueeze(1) @ torch.eye(8).unsqueeze(0))

torch.Size([3, 1])
torch.Size([1, 8, 8])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x8 and 1x3)

In [30]:
matrix = torch.eye(8)
print(torch.tensor([1,2,3]).reshape(-1,1,1))

tensor([[[1]],

        [[2]],

        [[3]]])


In [29]:
torch.bmm(input, torch.tensor([1,2,3]).reshape(-1,1,1) * matrix.repeat(3,1,1))

tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3., 3., 3., 3.]]])

In [7]:
from datasets.augmentations import AugmentationModuleSTFT
import torch
aug_module = AugmentationModuleSTFT(batch_size=32,
                                    time_mask_window=2,
                                    freq_mask_window=5)
input_stft = torch.rand(32,29,128)
output = aug_module(input_stft)